### POST - register a new user
POST http://127.0.0.1:5000/api/register
Content-Type: application/json

{
    "username": "testapiuser",
    "password": "testpassword"
}

### POST - login and get access token
POST http://127.0.0.1:5000/api/login
Content-Type: application/json

{
    "username": "testapiuser",
    "password": "testpassword"
}

### GET - list of movies for given user
GET http://127.0.0.1:5000/api/users/1/movies
